### PR TITLE
Refactor elasticsearch-asset-apis and add more powerful slicer APIs

### PR DESCRIPTION
**Pull request by peterdemartini**
- [x] Refactor the asset apis to make more sense
- [x] Add a lower level slicer API for getting the slice ranges
- [x] Add a lower level slicer API for slicing for a given range (not just an ID)
- [x] Fix `id_field_name` validation to work with the correct elasticsearch version
- [x] Fix issue getting a zero count for the whole query

### CODE REVIEW

**Review by jsnoble — COMMENTED** [review]
So a few questions:

1) what is supposed to be in  packages/elasticsearch-asset-apis/src/elasticsearch-reader-api/algorithms/utils.ts  ?

2) It seems like the date-helpers file is overloaded. It has the buildQuery and other functions that are used by both the ID and Date reader/slicers. Maybe that goes in the utils? It would make sense to only have date related code here if the name of the file stands as is

**Comment by peterdemartini** [comment]
> So a few questions:
> 
> 1. what is supposed to be in  packages/elasticsearch-asset-apis/src/elasticsearch-reader-api/algorithms/utils.ts  ?
> 2. It seems like the date-helpers file is overloaded. It has the buildQuery and other functions that are used by both the ID and Date reader/slicers. Maybe that goes in the utils? It would make sense to only have date related code here if the name of the file stands as is

1. Ahh ya that is where I meant to put  the `buildQuery` and other shared functions

**Comment by peterdemartini** [comment]
I manually test and bumped, this PR should be good to go

**Review by jsnoble — APPROVED** [review]
LGTM

**Pull request merged**
